apiVersion: apps/v1
kind: Deployment
metadata:
  name: nus-hacker-demo
  namespace: nus-hacker
  labels:
    app: nus-hacker-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nus-hacker-demo
  template:
    metadata:
      labels:
        app: nus-hacker-demo
    spec:
      containers:
      - name: app
        image: nus-hacker-demo:v1
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 0.1
            memory: 50Mi
          requests:
            cpu: 0.1
            memory: 50Mi
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 8080
