apiVersion: v1
kind: Service
metadata:
  name: nus-hacker-demo
  namespace: nus-hacker
spec:
  type: NodePort
  selector:
    app: nus-hacker-demo
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000